/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author wzamora
 */
public class guianum1 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public guianum1() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextLado1.requestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabelCubolado1 = new javax.swing.JLabel();
        jLabelCubolado2 = new javax.swing.JLabel();
        jLabellado1 = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jLabelArea = new javax.swing.JLabel();
        jLabelDiagonal = new javax.swing.JLabel();
        jLabelResDiagonal = new javax.swing.JLabel();
        jLabellado2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonDiametro = new javax.swing.JRadioButton();
        jButtonVolverMenu = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jRadioButtonDiametroEs = new javax.swing.JRadioButton();
        jButtonIrPromedio = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelCircunferencia = new javax.swing.JLabel();
        jRadioButtonRadio = new javax.swing.JRadioButton();
        jRadioButtonRadioEs = new javax.swing.JRadioButton();
        jButtonCalculoEs = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        jButtonCalcularRes = new javax.swing.JButton();
        jLabelResCircunferencia = new javax.swing.JLabel();
        jLabeltexto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldValorIngresado = new javax.swing.JTextField();
        jTextFieldBase = new javax.swing.JTextField();
        jLabelResArea = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextLado2 = new javax.swing.JTextField();
        jTextLado1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldValoringresadoEs = new javax.swing.JTextField();
        jTextFieldAltura = new javax.swing.JTextField();
        jTextFieldProfundidad = new javax.swing.JTextField();
        jLabelResVolumenEs = new javax.swing.JLabel();
        jButtonCalculoCubo = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabelResVol = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelCirculo = new javax.swing.JLabel();
        jLabelcuadro = new javax.swing.JLabel();
        jLabelEsfera = new javax.swing.JLabel();
        jLabelCubo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCubolado1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelCubolado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 40, 20));

        jLabelCubolado2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelCubolado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 40, 20));

        jLabellado1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabellado1.setForeground(new java.awt.Color(255, 255, 255));
        jLabellado1.setText("Lado 1");
        getContentPane().add(jLabellado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabelResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelResultado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResultado.setText("Resultados");
        getContentPane().add(jLabelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jButtonCalcular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabelArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelArea.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArea.setText("Area");
        getContentPane().add(jLabelArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabelDiagonal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDiagonal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDiagonal.setText("Diagonal");
        getContentPane().add(jLabelDiagonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabelResDiagonal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelResDiagonal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelResDiagonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 20));

        jLabellado2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabellado2.setForeground(new java.awt.Color(255, 255, 255));
        jLabellado2.setText("Lado 2");
        getContentPane().add(jLabellado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valor a ingresar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        buttonGroup1.add(jRadioButtonDiametro);
        jRadioButtonDiametro.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDiametro.setText("Diametro");
        getContentPane().add(jRadioButtonDiametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jButtonVolverMenu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVolverMenu.setText("Volver al menu");
        jButtonVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonExit.setText("Salir");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 70, -1));

        buttonGroup2.add(jRadioButtonDiametroEs);
        jRadioButtonDiametroEs.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDiametroEs.setText("Diametro");
        getContentPane().add(jRadioButtonDiametroEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jButtonIrPromedio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonIrPromedio.setText("Calcular el promedio de 10 numeros");
        jButtonIrPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrPromedioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIrPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Seleccione si el valor que ingresara es el radio o el diametro");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 370, -1));

        jLabelCircunferencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCircunferencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCircunferencia.setText("Circunferencia");
        getContentPane().add(jLabelCircunferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        buttonGroup1.add(jRadioButtonRadio);
        jRadioButtonRadio.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonRadio.setText("Radio");
        getContentPane().add(jRadioButtonRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        buttonGroup2.add(jRadioButtonRadioEs);
        jRadioButtonRadioEs.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonRadioEs.setText("Radio");
        jRadioButtonRadioEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRadioEsActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonRadioEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jButtonCalculoEs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCalculoEs.setText("Calcular");
        jButtonCalculoEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculoEsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalculoEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 80, -1));

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Valor a ingresar");
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 100, 20));

        jButtonCalcularRes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCalcularRes.setText("Calcular");
        jButtonCalcularRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularResActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcularRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabelResCircunferencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelResCircunferencia.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelResCircunferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 204, 100, 30));

        jLabeltexto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeltexto.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltexto.setText("Seleccione si el valor que ingresara es el radio o el diametro");
        getContentPane().add(jLabeltexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAzul.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 494, 600, 40));

        jTextFieldValorIngresado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldValorIngresadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorIngresadoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldValorIngresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 80, -1));

        jTextFieldBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBaseKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBaseKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 70, -1));

        jLabelResArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelResArea.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelResArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 90, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Altura");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jTextLado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextLado2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextLado2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextLado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 160, -1));

        jTextLado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLado1ActionPerformed(evt);
            }
        });
        jTextLado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextLado1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextLado1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextLado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 160, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Profundidad");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jTextFieldValoringresadoEs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldValoringresadoEsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValoringresadoEsKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldValoringresadoEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 80, -1));

        jTextFieldAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAlturaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAlturaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 70, -1));

        jTextFieldProfundidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldProfundidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProfundidadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldProfundidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 70, -1));

        jLabelResVolumenEs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelResVolumenEs.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelResVolumenEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 80, 30));

        jButtonCalculoCubo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCalculoCubo.setText("Calcular");
        jButtonCalculoCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculoCuboActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalculoCubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Volumen del objeto es");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabelResVol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelResVol.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelResVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 100, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Volumen del objeto es");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Base");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabelCirculo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelCirculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCirculo.setText("Calcula la circunferencia");
        getContentPane().add(jLabelCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabelcuadro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelcuadro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcuadro.setText("Calcular el area de un cuadrado");
        getContentPane().add(jLabelcuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 20));

        jLabelEsfera.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEsfera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEsfera.setText("Calcular el volumen de una Esfera");
        getContentPane().add(jLabelEsfera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabelCubo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCubo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCubo.setText("Calcular el volumen de un Cubo");
        getContentPane().add(jLabelCubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 220, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diapositiva1 - copia.JPG"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 100, 80));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo verde.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo rojo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 600, 130));

        jLabel3.setBackground(new java.awt.Color(255, 204, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo verde.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 600, 130));

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo rojo.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 143, 600, 390));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 600, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextLado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLado1ActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        if ((jTextLado2.getText().length() != 0) && (jTextLado1.getText().length() != 0)) {

            jLabelResDiagonal.setText("");
            jLabelCubolado1.setText("");
            jLabelCubolado2.setText("");
            jLabelResArea.setText("");
            double lado1;
            double lado2;
            double resul;
            double num;
            double resdiagonal;
            String res;
            String resdiagona;
            lado1 = Double.parseDouble(jTextLado1.getText());
            lado2 = Double.parseDouble(jTextLado2.getText());
            jLabelCubolado1.setText("" + lado1);
            jLabelCubolado2.setText("" + lado2);
            resul = lado1 * lado2;
            DecimalFormat df = new DecimalFormat("#.00");
            res = df.format(resul);
            jLabelResArea.setText("" + res);
            num = (double) ((Math.pow(lado1, 2)) + (Math.pow(lado2, 2)));
            resdiagonal = Math.sqrt(num);
            resdiagona = df.format(resdiagonal);
            jLabelResDiagonal.setText("" + resdiagona);
            jTextLado1.setText("");
            jTextLado2.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "los campos no pueden estar vacios");
        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jTextLado1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextLado1KeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextLado2.requestFocus(true);
        }
    }//GEN-LAST:event_jTextLado1KeyPressed

    private void jTextLado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextLado1KeyTyped
        char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextLado1.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextLado1KeyTyped

    private void jTextLado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextLado2KeyTyped
        char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextLado2.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }

    }//GEN-LAST:event_jTextLado2KeyTyped

    private void jButtonVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverMenuActionPerformed
        menu pagina = new menu();
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonVolverMenuActionPerformed

    private void jTextLado2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextLado2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ((jTextLado2.getText().length() != 0) && (jTextLado1.getText().length() != 0)) {
                jButtonCalcularActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            }
        }
    }//GEN-LAST:event_jTextLado2KeyPressed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonCalcularResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularResActionPerformed
        if ((jTextFieldValorIngresado.getText().length() != 0)) {
            jLabelResCircunferencia.setText("");
            if (jRadioButtonRadio.isSelected() || jRadioButtonDiametro.isSelected()) {
                double valorIngresado;
                double resultado;
                String res;
                valorIngresado = Double.parseDouble(jTextFieldValorIngresado.getText());
                if (jRadioButtonDiametro.isSelected()) {
                    resultado = 3.14 * valorIngresado;
                    DecimalFormat df = new DecimalFormat("#.00");
                    res = df.format(resultado);
                    jLabelResCircunferencia.setText(res);
                } else if (jRadioButtonRadio.isSelected()) {
                    resultado = 3.14 * (2 * valorIngresado);
                    DecimalFormat df = new DecimalFormat("#.00");
                    res = df.format(resultado);
                    jLabelResCircunferencia.setText(res);
                }
            } else {
                JOptionPane.showMessageDialog(null, "debe tener seleccionado ya sea 'Radio' o 'Diametro' \n no puede dejar vacio los dos botones");
            }
        } else {
            JOptionPane.showMessageDialog(null, "los campos no pueden estar vacios");
        }
    }//GEN-LAST:event_jButtonCalcularResActionPerformed

    private void jTextFieldValorIngresadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorIngresadoKeyTyped
        char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldValorIngresado.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldValorIngresadoKeyTyped

    private void jTextFieldValorIngresadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorIngresadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTextFieldValorIngresado.getText().length() != 0) {
                jButtonCalcularResActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            }
        }
    }//GEN-LAST:event_jTextFieldValorIngresadoKeyPressed

    private void jRadioButtonRadioEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRadioEsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRadioEsActionPerformed

    private void jButtonCalculoEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculoEsActionPerformed
        if ((jTextFieldValoringresadoEs.getText().length() != 0)) {
            if (jRadioButtonRadioEs.isSelected() || jRadioButtonDiametroEs.isSelected()) {
                double valorIngresado;
                double resultado;
                String res;
                valorIngresado = Double.parseDouble(jTextFieldValoringresadoEs.getText());
                if (jRadioButtonDiametroEs.isSelected()) {
                    valorIngresado = valorIngresado / 2;
                    valorIngresado = Math.pow(valorIngresado, 3);
                    resultado = (1.33333) * 3.141559 * (valorIngresado);
                    DecimalFormat df = new DecimalFormat("#.00");
                    res = df.format(resultado);
                    jLabelResVolumenEs.setText(res);
                } else if (jRadioButtonRadioEs.isSelected()) {
                    valorIngresado = Math.pow(valorIngresado, 3);
                    resultado = (1.33333) * 3.14159 * (valorIngresado);
                    DecimalFormat df = new DecimalFormat("#.00");
                    res = df.format(resultado);
                    jLabelResVolumenEs.setText(res);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe Seleccionar si es radio o diametro ese valor no puede quedar vacio");
            }
        }else {
                JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
        }
    }//GEN-LAST:event_jButtonCalculoEsActionPerformed

    private void jButtonCalculoCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculoCuboActionPerformed
        if ((jTextFieldBase.getText().length() != 0) && (jTextFieldAltura.getText().length() != 0) && (jTextFieldProfundidad.getText().length() != 0)) {
            double base;
            double altura;
            double profundidad;
            Double respuesta;
            String res;
            base = Double.parseDouble(jTextFieldBase.getText());
            altura = Double.parseDouble(jTextFieldAltura.getText());
            profundidad = Double.parseDouble(jTextFieldProfundidad.getText());
            respuesta = base * altura * profundidad;
            DecimalFormat df = new DecimalFormat("#.00");
            res = df.format(respuesta);
            jLabelResVol.setText(res);

        } else {
            JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
        }
    }//GEN-LAST:event_jButtonCalculoCuboActionPerformed

    private void jTextFieldValoringresadoEsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValoringresadoEsKeyTyped
        char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldValoringresadoEs.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldValoringresadoEsKeyTyped

    private void jTextFieldValoringresadoEsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValoringresadoEsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ((jTextFieldValoringresadoEs.getText().length() != 0)) {
                jButtonCalculoEsActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(null, "El campo no puede estar vacio");
            }
        }
    }//GEN-LAST:event_jTextFieldValoringresadoEsKeyPressed

    private void jTextFieldBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBaseKeyTyped
        char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldBase.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldBaseKeyTyped

    private void jTextFieldAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlturaKeyTyped
        char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldAltura.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldAlturaKeyTyped

    private void jTextFieldProfundidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProfundidadKeyTyped
        char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldProfundidad.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldProfundidadKeyTyped

    private void jTextFieldBaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBaseKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
        jTextFieldAltura.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldBaseKeyPressed

    private void jTextFieldAlturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlturaKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
        jTextFieldProfundidad.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldAlturaKeyPressed

    private void jTextFieldProfundidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProfundidadKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
        jButtonCalculoCuboActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldProfundidadKeyPressed

    private void jButtonIrPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrPromedioActionPerformed
         promedioDe10numeros pagina = new promedioDe10numeros();
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonIrPromedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guianum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new guianum1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonCalcularRes;
    private javax.swing.JButton jButtonCalculoCubo;
    private javax.swing.JButton jButtonCalculoEs;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonIrPromedio;
    private javax.swing.JButton jButtonVolverMenu;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelArea;
    private javax.swing.JLabel jLabelCirculo;
    private javax.swing.JLabel jLabelCircunferencia;
    private javax.swing.JLabel jLabelCubo;
    private javax.swing.JLabel jLabelCubolado1;
    private javax.swing.JLabel jLabelCubolado2;
    private javax.swing.JLabel jLabelDiagonal;
    private javax.swing.JLabel jLabelEsfera;
    private javax.swing.JLabel jLabelResArea;
    private javax.swing.JLabel jLabelResCircunferencia;
    private javax.swing.JLabel jLabelResDiagonal;
    private javax.swing.JLabel jLabelResVol;
    private javax.swing.JLabel jLabelResVolumenEs;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelcuadro;
    private javax.swing.JLabel jLabellado1;
    private javax.swing.JLabel jLabellado2;
    private javax.swing.JLabel jLabeltexto;
    private javax.swing.JRadioButton jRadioButtonDiametro;
    private javax.swing.JRadioButton jRadioButtonDiametroEs;
    private javax.swing.JRadioButton jRadioButtonRadio;
    private javax.swing.JRadioButton jRadioButtonRadioEs;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldBase;
    private javax.swing.JTextField jTextFieldProfundidad;
    private javax.swing.JTextField jTextFieldValorIngresado;
    private javax.swing.JTextField jTextFieldValoringresadoEs;
    private javax.swing.JTextField jTextLado1;
    private javax.swing.JTextField jTextLado2;
    // End of variables declaration//GEN-END:variables
}
