/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import com.sun.glass.events.KeyEvent;
import static java.util.Arrays.sort;
import javax.swing.JOptionPane;

/**
 *
 * @author fam. moreno
 */
public class Guianum2 extends javax.swing.JFrame {

    /**
     * Creates new form Guianum2
     */
    public Guianum2() {
        initComponents();
        Lista = new String[10];
        this.setLocationRelativeTo(null);
        jButtonIngresar.setEnabled(false);
        jTextCaracterIngresado.setEnabled(false);
        jButtonVer.setEnabled(false);
        jButtonOrdenar.setEnabled(false);
        jTextAreaHoja.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHoja = new javax.swing.JTextArea();
        jButtonVer = new javax.swing.JButton();
        jButtonOrdenar = new javax.swing.JButton();
        jTextCaracterIngresado = new javax.swing.JTextField();
        jButtonIngresar = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresar datos", "Ordenar datos", "Ver datos" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jTextAreaHoja.setColumns(20);
        jTextAreaHoja.setRows(5);
        jScrollPane1.setViewportView(jTextAreaHoja);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 226, 290, 120));

        jButtonVer.setText("ver");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 70, -1));

        jButtonOrdenar.setText("Ordenar");
        jButtonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jTextCaracterIngresado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCaracterIngresadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCaracterIngresadoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextCaracterIngresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 100, -1));

        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jButtonRegresar.setText("Regresar al menu");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese el caracter ENTER para ingresar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione la opcion deseada");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Guia numero 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 434));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed

        Lista[num] = jTextCaracterIngresado.getText();
        num = num + 1;
        if (num == 10) {
            jTextCaracterIngresado.setEnabled(false);
            jButtonIngresar.setEnabled(false);
        }
        jTextCaracterIngresado.setText("");
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jTextCaracterIngresadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCaracterIngresadoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonIngresarActionPerformed(null);
        }
    }//GEN-LAST:event_jTextCaracterIngresadoKeyPressed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        String salida = "";
        for (int posicion = 0; posicion < 10; posicion++) {
            salida = salida + Lista[posicion] + "\n";
        }
        JOptionPane.showMessageDialog(null, salida);
        jTextAreaHoja.setText(salida);
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        menu pagina = new menu();
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() == 0) {
            jButtonIngresar.setEnabled(true);
            jTextCaracterIngresado.setEnabled(true);
            jButtonVer.setEnabled(false);
            jButtonOrdenar.setEnabled(false);
        } else if (jComboBox1.getSelectedIndex() == 1) {
            jButtonOrdenar.setEnabled(true);
            jButtonIngresar.setEnabled(false);
            jTextCaracterIngresado.setEnabled(false);
            jButtonVer.setEnabled(false);
        } else if (jComboBox1.getSelectedIndex() == 2) {
            jButtonVer.setEnabled(true);
            jButtonOrdenar.setEnabled(false);
            jButtonIngresar.setEnabled(false);
            jTextCaracterIngresado.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextCaracterIngresadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCaracterIngresadoKeyTyped
        char letra = evt.getKeyChar();
        if (Character.isLetter(letra)) {

        } else {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            
        }else{
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar letras");
        }
        }
    }//GEN-LAST:event_jTextCaracterIngresadoKeyTyped

    private void jButtonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarActionPerformed
       
    }//GEN-LAST:event_jButtonOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guianum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guianum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guianum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guianum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guianum2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonOrdenar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaHoja;
    private javax.swing.JTextField jTextCaracterIngresado;
    // End of variables declaration//GEN-END:variables
String Lista[];
    int num = 0;
}
