/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author fam. moreno
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGuia1 = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jButtonGuia2 = new javax.swing.JButton();
        jButtonGuia3y4 = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonGuia1.setBackground(new java.awt.Color(102, 255, 102));
        jButtonGuia1.setFont(new java.awt.Font("LAIKA", 2, 24)); // NOI18N
        jButtonGuia1.setText("Guia numero 1");
        jButtonGuia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuia1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 59, 239, -1));

        jButtonRegresar.setBackground(new java.awt.Color(0, 153, 153));
        jButtonRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegresar.setText("Cerrar secion");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 130, 30));

        jButtonGuia2.setBackground(new java.awt.Color(204, 204, 255));
        jButtonGuia2.setFont(new java.awt.Font("LAIKA", 2, 24)); // NOI18N
        jButtonGuia2.setText("Guia numero 2");
        jButtonGuia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuia2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 110, 239, 38));

        jButtonGuia3y4.setBackground(new java.awt.Color(255, 204, 204));
        jButtonGuia3y4.setFont(new java.awt.Font("LAIKA", 2, 24)); // NOI18N
        jButtonGuia3y4.setText("Guia numero 3y4");
        jButtonGuia3y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuia3y4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuia3y4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 166, -1, 31));

        jButtonSalir.setBackground(new java.awt.Color(153, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 231, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo verde.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuia2ActionPerformed
       Guianum2 guia2 = new Guianum2();
            this.setVisible(false);
            guia2.setVisible(true);
            guia2.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonGuia2ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonGuia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuia1ActionPerformed
        guianum1 guia = new guianum1();
            this.setVisible(false);
            guia.setVisible(true);
            guia.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonGuia1ActionPerformed

    private void jButtonGuia3y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuia3y4ActionPerformed
        frmPuntaje guia3 = new frmPuntaje();
            this.setVisible(false);
            guia3.setVisible(true);
            guia3.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonGuia3y4ActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
       Login pagina = new Login();
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuia1;
    private javax.swing.JButton jButtonGuia2;
    private javax.swing.JButton jButtonGuia3y4;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
