/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author fam. moreno
 */
public class promedioDe10numeros extends javax.swing.JFrame {

    /**
     * Creates new form promedioDe10numeros
     */
    public promedioDe10numeros() {
        initComponents();
        jTextFieldNum1.requestFocus();
        double cadenaDeNumeros [];
        cadenaDeNumeros = new double[10];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldNum1 = new javax.swing.JTextField();
        jTextFieldNum2 = new javax.swing.JTextField();
        jTextFieldNum3 = new javax.swing.JTextField();
        jTextFieldNum4 = new javax.swing.JTextField();
        jTextFieldNum5 = new javax.swing.JTextField();
        jTextFieldNum6 = new javax.swing.JTextField();
        jTextFieldNum7 = new javax.swing.JTextField();
        jTextFieldNum8 = new javax.swing.JTextField();
        jTextFieldNum9 = new javax.swing.JTextField();
        jTextFieldNum10 = new javax.swing.JTextField();
        jLabelRespuesta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCalcularProm = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonguia1 = new javax.swing.JButton();
        jLabelRes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calcular el promedio de 10 numeros");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTextFieldNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNum1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNum1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, -1));

        jTextFieldNum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNum2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNum2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 60, -1));

        jTextFieldNum3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNum3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNum3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 50, -1));

        jTextFieldNum4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNum4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNum4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 60, -1));

        jTextFieldNum5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNum5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNum5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 60, -1));

        jTextFieldNum6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNum6KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNum6KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 60, -1));

        jTextFieldNum7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNum7KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNum7KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNum7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 60, -1));

        jTextFieldNum8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNum8KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNum8KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNum8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 50, -1));

        jTextFieldNum9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNum9KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNum9KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNum9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 60, -1));

        jTextFieldNum10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNum10KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNum10KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNum10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 60, -1));

        jLabelRespuesta.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabelRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 70, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Numero 9");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 60, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero 10");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 60, -1));

        jButtonCalcularProm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCalcularProm.setText("Calcular");
        jButtonCalcularProm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularPromActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcularProm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVolver.setText("Volver al menu");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jButtonguia1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonguia1.setText("Volver a guia 1");
        jButtonguia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonguia1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonguia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabelRes.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelRes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRes.setText("El promedio es:");
        getContentPane().add(jLabelRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero 1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero 2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Numero 3");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numero 4");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Numero 5");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Numero 6");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Numero 7");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Numero 8");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo verde.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularPromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularPromActionPerformed
        
        double suma;
        double numero1, numero2, numero3, numero4, numero5, numero6, numero7, numero8, numero9, numero10;
        double resultado;
        String res;
        numero1 = (Double.parseDouble(jTextFieldNum1.getText()));
        numero2 = (Double.parseDouble(jTextFieldNum2.getText()));
        numero3 = (Double.parseDouble(jTextFieldNum3.getText()));
        numero4 = (Double.parseDouble(jTextFieldNum4.getText()));
        numero5 = (Double.parseDouble(jTextFieldNum5.getText()));
        numero6 = (Double.parseDouble(jTextFieldNum6.getText()));
        numero7 = (Double.parseDouble(jTextFieldNum7.getText()));
        numero8 = (Double.parseDouble(jTextFieldNum8.getText()));
        numero9 = (Double.parseDouble(jTextFieldNum9.getText()));
        numero10 = (Double.parseDouble(jTextFieldNum10.getText()));
        DecimalFormat df = new DecimalFormat("#.00");        
        suma = numero1 +numero2+numero3+numero4+numero5+numero6+numero7+numero8+numero9+numero10;
        resultado = suma/10;
        res = df.format(resultado);
        jLabelRespuesta.setText(res);
        
    }//GEN-LAST:event_jButtonCalcularPromActionPerformed

    private void jTextFieldNum1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNum2.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldNum1KeyPressed

    private void jTextFieldNum2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNum3.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldNum2KeyPressed

    private void jTextFieldNum3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum3KeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNum4.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldNum3KeyPressed

    private void jTextFieldNum4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum4KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNum5.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldNum4KeyPressed

    private void jTextFieldNum5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum5KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNum6.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldNum5KeyPressed

    private void jTextFieldNum6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum6KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNum7.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldNum6KeyPressed

    private void jTextFieldNum7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum7KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNum8.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldNum7KeyPressed

    private void jTextFieldNum8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum8KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNum9.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldNum8KeyPressed

    private void jTextFieldNum9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum9KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNum10.requestFocus(true);
        }
    }//GEN-LAST:event_jTextFieldNum9KeyPressed

    private void jTextFieldNum10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum10KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonCalcularPromActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldNum10KeyPressed

    private void jTextFieldNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum1KeyTyped
         char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldNum1.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldNum1KeyTyped

    private void jTextFieldNum2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum2KeyTyped
         char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldNum2.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldNum2KeyTyped

    private void jTextFieldNum3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum3KeyTyped
         char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldNum3.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldNum3KeyTyped

    private void jTextFieldNum4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum4KeyTyped
         char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldNum4.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldNum4KeyTyped

    private void jTextFieldNum5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum5KeyTyped
         char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldNum5.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldNum5KeyTyped

    private void jTextFieldNum6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum6KeyTyped
         char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldNum6.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldNum6KeyTyped

    private void jTextFieldNum7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum7KeyTyped
         char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldNum7.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldNum7KeyTyped

    private void jTextFieldNum8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum8KeyTyped
         char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldNum8.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldNum8KeyTyped

    private void jTextFieldNum9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum9KeyTyped
         char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldNum9.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldNum9KeyTyped

    private void jTextFieldNum10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNum10KeyTyped
         char letra = evt.getKeyChar();
        if (!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar() != '.'){
        evt.consume();
        }
        if(evt.getKeyChar()=='.' && jTextFieldNum10.getText().contains(".")){
        evt.consume();
        }
        if(Character.isSpaceChar(letra)){
        JOptionPane.showMessageDialog(null, "no puede introducir espacios");
        }
        if (Character.isLetter(letra)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo puede ingresar numeros");
        } else {

        }
    }//GEN-LAST:event_jTextFieldNum10KeyTyped

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
         menu pagina = new menu();
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonguia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonguia1ActionPerformed
         guianum1 pagina = new guianum1();
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonguia1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(promedioDe10numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(promedioDe10numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(promedioDe10numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(promedioDe10numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new promedioDe10numeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcularProm;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JButton jButtonguia1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRes;
    private javax.swing.JLabel jLabelRespuesta;
    private javax.swing.JTextField jTextFieldNum1;
    private javax.swing.JTextField jTextFieldNum10;
    private javax.swing.JTextField jTextFieldNum2;
    private javax.swing.JTextField jTextFieldNum3;
    private javax.swing.JTextField jTextFieldNum4;
    private javax.swing.JTextField jTextFieldNum5;
    private javax.swing.JTextField jTextFieldNum6;
    private javax.swing.JTextField jTextFieldNum7;
    private javax.swing.JTextField jTextFieldNum8;
    private javax.swing.JTextField jTextFieldNum9;
    // End of variables declaration//GEN-END:variables
}
