/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topografiap;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author PC30
 */
public class IngresarNuevo extends javax.swing.JFrame {

    /**
     * Creates new form IngresarNuevo
     */
    public IngresarNuevo() {
        initComponents();
        this.setMinimumSize(new Dimension(400, 400));
        this.setLocationRelativeTo(null);
        grupodebtn.add(vistaaf);
        grupodebtn.add(vistaat);
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField13 = new javax.swing.JTextField();
        grupodebtn = new javax.swing.ButtonGroup();
        jBtnCancelar = new javax.swing.JButton();
        tabbedp = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNVertices = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTAGrados = new javax.swing.JTextField();
        txtTAMinutos = new javax.swing.JTextField();
        txtTASegundos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAIGrados = new javax.swing.JTextField();
        txtAIMinutos = new javax.swing.JTextField();
        txtAISegundos = new javax.swing.JTextField();
        vistaaf = new javax.swing.JRadioButton();
        vistaat = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        txtLatitud = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNMojones = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtL4Grados = new javax.swing.JTextField();
        txtL4Minutos = new javax.swing.JTextField();
        txtL4Segundos = new javax.swing.JTextField();
        txtL3Grados = new javax.swing.JTextField();
        txtL3Minutos = new javax.swing.JTextField();
        txtL3Segundos = new javax.swing.JTextField();
        txtL2Grados = new javax.swing.JTextField();
        txtL1Grados = new javax.swing.JTextField();
        txtL2Minutos = new javax.swing.JTextField();
        txtL2Segundos = new javax.swing.JTextField();
        txtL1Segundos = new javax.swing.JTextField();
        txtL1Minutos = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtDisXEst = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEstacion = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtDeflexionG = new javax.swing.JTextField();
        txtDeflexionM = new javax.swing.JTextField();
        txtDeflexionS = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtDisXMoj = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jTextField13.setText("jTextField13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingrese Valores");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        tabbedp.setBackground(new java.awt.Color(153, 153, 153));
        tabbedp.setForeground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("numero de vertices");

        txtNVertices.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNVerticesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNVerticesKeyTyped(evt);
            }
        });

        jLabel9.setText("Tolerancia angular");

        txtTAGrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTAGradosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTAGradosKeyTyped(evt);
            }
        });

        txtTAMinutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTAMinutosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTAMinutosKeyTyped(evt);
            }
        });

        txtTASegundos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTASegundosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTASegundosKeyTyped(evt);
            }
        });

        jLabel10.setText("Azimut inicial");

        txtAIGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAIGradosActionPerformed(evt);
            }
        });
        txtAIGrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAIGradosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAIGradosKeyTyped(evt);
            }
        });

        txtAIMinutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAIMinutosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAIMinutosKeyTyped(evt);
            }
        });

        txtAISegundos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAISegundosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAISegundosKeyTyped(evt);
            }
        });

        vistaaf.setText("Vista al frente");

        vistaat.setText("Vista atras");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Datos Generales");

        jButton1.setText("siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 316, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNVertices, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtAIGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtAIMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtTAGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtTAMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTASegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAISegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(vistaaf)
                .addGap(18, 18, 18)
                .addComponent(vistaat)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNVertices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTASegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTAMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTAGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAIGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAIMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAISegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vistaaf)
                    .addComponent(vistaat))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        tabbedp.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Coordenada inicial");

        jLabel13.setText("Longitud");

        jLabel14.setText("Latitud");

        txtLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudActionPerformed(evt);
            }
        });
        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLongitudKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });

        txtLatitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLatitudKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLatitudKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Terreno");

        jLabel16.setText("Numero de mojones");

        txtNMojones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNMojonesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNMojonesKeyTyped(evt);
            }
        });

        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLatitud, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(txtLongitud, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(txtNMojones, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel15)))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(txtLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNMojones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(21, 21, 21))
        );

        tabbedp.addTab("tab2", jPanel2);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel24.setText("lectura #4");

        jLabel25.setText("lectura #3");

        jLabel26.setText("lectura #2");

        jLabel27.setText("lectura #1");

        txtL4Grados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtL4GradosActionPerformed(evt);
            }
        });
        txtL4Grados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL4GradosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL4GradosKeyTyped(evt);
            }
        });

        txtL4Minutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtL4MinutosActionPerformed(evt);
            }
        });
        txtL4Minutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL4MinutosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL4MinutosKeyTyped(evt);
            }
        });

        txtL4Segundos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL4SegundosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL4SegundosKeyTyped(evt);
            }
        });

        txtL3Grados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL3GradosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL3GradosKeyTyped(evt);
            }
        });

        txtL3Minutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtL3MinutosActionPerformed(evt);
            }
        });
        txtL3Minutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL3MinutosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL3MinutosKeyTyped(evt);
            }
        });

        txtL3Segundos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL3SegundosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL3SegundosKeyTyped(evt);
            }
        });

        txtL2Grados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        txtL2Grados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL2GradosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL2GradosKeyTyped(evt);
            }
        });

        txtL1Grados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL1GradosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL1GradosKeyTyped(evt);
            }
        });

        txtL2Minutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL2MinutosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL2MinutosKeyTyped(evt);
            }
        });

        txtL2Segundos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL2SegundosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL2SegundosKeyTyped(evt);
            }
        });

        txtL1Segundos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL1SegundosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL1SegundosKeyTyped(evt);
            }
        });

        txtL1Minutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtL1MinutosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtL1MinutosKeyTyped(evt);
            }
        });

        jLabel28.setText("grados");

        jLabel29.setText("minutos");

        jLabel30.setText("segundos");

        jLabel32.setText("Distancia");

        txtDisXEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisXEstActionPerformed(evt);
            }
        });
        txtDisXEst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDisXEstKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisXEstKeyTyped(evt);
            }
        });

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Siguiente");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Estacion");

        txtEstacion.setText("1");
        txtEstacion.setEnabled(false);

        jButton7.setText("Anterior");

        jButton8.setText("Siguiente");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtL2Grados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(txtL3Grados, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtL4Grados, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtL1Grados))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtL3Minutos, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(txtL2Minutos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtL1Minutos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtL4Minutos))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtL1Segundos)
                    .addComponent(txtL2Segundos)
                    .addComponent(txtL4Segundos)
                    .addComponent(txtL3Segundos))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDisXEst, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButton6))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel28)
                .addGap(75, 75, 75)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(171, 171, 171))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtL4Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtL4Segundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtL4Grados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtL3Segundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtL3Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtL3Grados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtL2Grados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL2Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtL2Segundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtL1Grados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtL1Minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtL1Segundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDisXEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        tabbedp.addTab("tab3", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Mojones");

        jLabel34.setText("Deflexion");

        txtDeflexionG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDeflexionGKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDeflexionGKeyTyped(evt);
            }
        });

        txtDeflexionM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDeflexionMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDeflexionMKeyTyped(evt);
            }
        });

        txtDeflexionS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDeflexionSKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDeflexionSKeyTyped(evt);
            }
        });

        jLabel35.setText("Distancia");

        txtDisXMoj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDisXMojKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisXMojKeyTyped(evt);
            }
        });

        jButton10.setText("Guardar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("regresar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeflexionG, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDisXMoj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDeflexionM, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDeflexionS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(35, 35, 35))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel33)
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel34)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDeflexionG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDeflexionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDeflexionS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDisXMoj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton10))
                .addGap(20, 20, 20))
        );

        tabbedp.addTab("tab4", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedp)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jBtnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabbedp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void txtNVerticesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNVerticesKeyTyped
        int limite = 10;
        if (txtNVertices.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9]")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNVerticesKeyTyped

    private void txtNVerticesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNVerticesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtTAGrados.requestFocus();
        }
    }//GEN-LAST:event_txtNVerticesKeyPressed

    private void txtAIGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAIGradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAIGradosActionPerformed

    private void txtTAGradosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTAGradosKeyTyped
        int limite = 10;
        if (txtTAGrados.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtTAGrados.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTAGradosKeyTyped

    private void txtTAGradosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTAGradosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtTAMinutos.requestFocus();
        }
    }//GEN-LAST:event_txtTAGradosKeyPressed

    private void txtTAMinutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTAMinutosKeyTyped
         int limite = 10;
        if (txtTAMinutos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtTAMinutos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTAMinutosKeyTyped

    private void txtTAMinutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTAMinutosKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtTASegundos.requestFocus();
        }
    }//GEN-LAST:event_txtTAMinutosKeyPressed

    private void txtTASegundosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTASegundosKeyTyped
         int limite = 10;
        if (txtTASegundos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtTASegundos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTASegundosKeyTyped

    private void txtTASegundosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTASegundosKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAIGrados.requestFocus();
        }
    }//GEN-LAST:event_txtTASegundosKeyPressed

    private void txtAIGradosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAIGradosKeyTyped
        int limite = 10;
        if (txtAIGrados.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtAIGrados.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAIGradosKeyTyped

    private void txtAIGradosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAIGradosKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAIMinutos.requestFocus();
        }
    }//GEN-LAST:event_txtAIGradosKeyPressed

    private void txtAIMinutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAIMinutosKeyTyped
        int limite = 10;
        if (txtAIMinutos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtAIMinutos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAIMinutosKeyTyped

    private void txtAIMinutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAIMinutosKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAISegundos.requestFocus();
        }
    }//GEN-LAST:event_txtAIMinutosKeyPressed

    private void txtAISegundosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAISegundosKeyTyped
         int limite = 10;
        if (txtAISegundos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtAISegundos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAISegundosKeyTyped

    private void txtAISegundosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAISegundosKeyPressed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtAISegundosKeyPressed

    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped
         int limite = 10;
        if (txtLongitud.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtLongitud.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtLongitudKeyTyped

    private void txtLongitudKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtLatitud.requestFocus();
        }
    }//GEN-LAST:event_txtLongitudKeyPressed

    private void txtLatitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLatitudKeyTyped
         int limite = 10;
        if (txtLatitud.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtLatitud.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtLatitudKeyTyped

    private void txtLatitudKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLatitudKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNMojones.requestFocus();
        }
    }//GEN-LAST:event_txtLatitudKeyPressed

    private void txtNMojonesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNMojonesKeyTyped
        int limite = 10;
        if (txtNMojones.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9]")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNMojonesKeyTyped

    private void txtNMojonesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNMojonesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNMojonesKeyPressed

    private void txtDeflexionGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeflexionGKeyTyped
        int limite = 10;
        if (txtDeflexionG.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtDeflexionG.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDeflexionGKeyTyped

    private void txtDeflexionGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeflexionGKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDeflexionM.requestFocus();
        }
    }//GEN-LAST:event_txtDeflexionGKeyPressed

    private void txtDeflexionMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeflexionMKeyTyped
        int limite = 10;
        if (txtDeflexionM.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtDeflexionM.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDeflexionMKeyTyped

    private void txtDeflexionMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeflexionMKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDeflexionS.requestFocus();
        }
    }//GEN-LAST:event_txtDeflexionMKeyPressed

    private void txtDeflexionSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeflexionSKeyTyped
        int limite = 10;
        if (txtDeflexionS.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtDeflexionS.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDeflexionSKeyTyped

    private void txtDeflexionSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeflexionSKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDisXMoj.requestFocus();
        }
    }//GEN-LAST:event_txtDeflexionSKeyPressed

    private void txtDisXMojKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisXMojKeyTyped
        int limite = 10;
        if (txtDisXMoj.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtDisXMoj.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDisXMojKeyTyped

    private void txtDisXMojKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisXMojKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisXMojKeyPressed

    private void txtDisXEstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisXEstKeyTyped
        int limite = 10;
        if (txtDisXEst.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtDisXEst.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDisXEstKeyTyped

    private void txtDisXEstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisXEstKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisXEstKeyPressed

    private void txtL2SegundosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL2SegundosKeyTyped
        int limite = 10;
        if (txtL2Segundos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL2Segundos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL2SegundosKeyTyped

    private void txtL2SegundosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL2SegundosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL1Grados.requestFocus();
        }
    }//GEN-LAST:event_txtL2SegundosKeyPressed

    private void txtL2MinutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL2MinutosKeyTyped
        int limite = 10;
        if (txtL2Minutos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL2Minutos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL2MinutosKeyTyped

    private void txtL2MinutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL2MinutosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL2Segundos.requestFocus();
        }
    }//GEN-LAST:event_txtL2MinutosKeyPressed

    private void txtL2GradosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL2GradosKeyTyped
        int limite = 10;
        if (txtL2Grados.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL2Grados.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL2GradosKeyTyped

    private void txtL2GradosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL2GradosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL2Minutos.requestFocus();
        }
    }//GEN-LAST:event_txtL2GradosKeyPressed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void txtL1GradosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL1GradosKeyTyped
        int limite = 10;
        if (txtL1Grados.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL1Grados.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL1GradosKeyTyped

    private void txtL1GradosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL1GradosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL1Minutos.requestFocus();
        }
    }//GEN-LAST:event_txtL1GradosKeyPressed

    private void txtL1SegundosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL1SegundosKeyTyped
        int limite = 10;
        if (txtL1Segundos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL1Segundos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL1SegundosKeyTyped

    private void txtL1SegundosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL1SegundosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDisXEst.requestFocus();
        }
    }//GEN-LAST:event_txtL1SegundosKeyPressed

    private void txtL1MinutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL1MinutosKeyTyped
        int limite = 10;
        if (txtL1Minutos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL1Minutos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL1MinutosKeyTyped

    private void txtL1MinutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL1MinutosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL1Segundos.requestFocus();
        }
    }//GEN-LAST:event_txtL1MinutosKeyPressed

    private void txtL3SegundosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL3SegundosKeyTyped
        int limite = 10;
        if (txtL3Segundos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL3Segundos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL3SegundosKeyTyped

    private void txtL3SegundosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL3SegundosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL2Grados.requestFocus();
        }
    }//GEN-LAST:event_txtL3SegundosKeyPressed

    private void txtL3MinutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL3MinutosKeyTyped
        int limite = 10;
        if (txtL3Minutos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL3Minutos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL3MinutosKeyTyped

    private void txtL3MinutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL3MinutosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL3Segundos.requestFocus();
        }
    }//GEN-LAST:event_txtL3MinutosKeyPressed

    private void txtL3GradosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL3GradosKeyTyped
        int limite = 10;
        if (txtL3Grados.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL3Grados.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL3GradosKeyTyped

    private void txtL3GradosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL3GradosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL3Minutos.requestFocus();
        }
    }//GEN-LAST:event_txtL3GradosKeyPressed

    private void txtL4SegundosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL4SegundosKeyTyped
        int limite = 10;
        if (txtL4Segundos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL4Segundos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL4SegundosKeyTyped

    private void txtL4SegundosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL4SegundosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL3Grados.requestFocus();
        }
    }//GEN-LAST:event_txtL4SegundosKeyPressed

    private void txtL4MinutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL4MinutosKeyTyped
        int limite = 10;
        if (txtL4Minutos.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL4Minutos.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL4MinutosKeyTyped

    private void txtL4MinutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL4MinutosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL4Segundos.requestFocus();
        }
    }//GEN-LAST:event_txtL4MinutosKeyPressed

    private void txtL4GradosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL4GradosKeyTyped
        int limite = 10;
        if (txtL4Grados.getText().length() > limite) {
            evt.consume();
        }
        char dato = evt.getKeyChar();
        String cadena = "" + dato;
        if (!cadena.matches("[0-9.]")) {
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && txtL4Grados.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtL4GradosKeyTyped

    private void txtL4GradosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtL4GradosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtL4Minutos.requestFocus();
        }
    }//GEN-LAST:event_txtL4GradosKeyPressed

    private void txtL4GradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtL4GradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtL4GradosActionPerformed

    private void txtL4MinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtL4MinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtL4MinutosActionPerformed

    private void txtL3MinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtL3MinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtL3MinutosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtNVertices.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Debe ingresar el numero de vertices");
        txtNVertices.requestFocus();
        }else if (txtTAGrados.getText().isEmpty() && txtTAMinutos.getText().isEmpty() && txtTASegundos.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "debe ingresar la tolerancia");
           txtTAGrados.requestFocus();
        }else if(txtAIGrados.getText().isEmpty() && txtAIMinutos.getText().isEmpty() && txtAISegundos.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "debe ingresar el azimut inicial");
        txtAIGrados.requestFocus();
        }else if(vistaaf.isSelected()==false && vistaat.isSelected()==false){ 
            JOptionPane.showMessageDialog(this, "Debe de seleccionar que tipo de vista utilizo");}
            else{
        tabbedp.setSelectedIndex(1); 
        
       Calculo.CrearMatris(Integer.parseInt(txtNVertices.getText()));
        
      
        }       // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
tabbedp.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(txtLongitud.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Debe ingresar la longitud de la coordenada inicial");
        txtLongitud.requestFocus();
        }else if(txtLatitud.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Debe ingresar la Latitud");
        txtLatitud.requestFocus();
        }else if(txtNMojones.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Debe ingresar el numero de mojones");
        txtNMojones.requestFocus();
        }else{
        tabbedp.setSelectedIndex(2); }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
tabbedp.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(txtL4Grados.getText().isEmpty() && txtL4Minutos.getText().isEmpty() && txtL4Segundos.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Debe ingresar la cuarta lectura");
        txtL4Grados.requestFocus();}
        else if(txtL3Grados.getText().isEmpty() && txtL3Minutos.getText().isEmpty() && txtL3Segundos.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Debe ingresar la tercera lectura");
         txtL3Grados.requestFocus();
        }else if(txtL2Grados.getText().isEmpty() && txtL2Minutos.getText().isEmpty() && txtL2Segundos.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Debe ingresar la segunda lectura");
        txtL2Grados.requestFocus();}
        else if(txtL1Grados.getText().isEmpty() && txtL1Minutos.getText().isEmpty() && txtL1Segundos.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Debe ingresar la primera lectura");
        txtL1Grados.requestFocus();}
        else if(txtDisXEst.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Debe ingresar la distancia");
        txtDisXEst.requestFocus();
        }else{
        tabbedp.setSelectedIndex(3);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
tabbedp.setSelectedIndex(2);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitudActionPerformed

    private void txtDisXEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisXEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisXEstActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    if(txtDeflexionG.getText().isEmpty() && txtDeflexionM.getText().isEmpty() && txtDeflexionS.getText().isEmpty()){        // TODO add your handling code here:
    JOptionPane.showMessageDialog(this, "Debe ingresar la Deflexion");
    txtDeflexionG.requestFocus();
    }else if(txtDisXMoj.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "Debe ingresar la distancia");
    txtDisXMoj.requestFocus();
    }    
    }//GEN-LAST:event_jButton10ActionPerformed
 
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       if(Integer.parseInt(txtEstacion.getText())<Integer.parseInt(txtNVertices.getText())){
       int numero = Integer.parseInt(txtEstacion.getText());
           
           
           
          Double Lectura1, Lectura2, Lectura3, Lectura4;
        
        
          Lectura1 = Calculo.conversion(Double.parseDouble(txtL1Grados.getText()),Double.parseDouble(txtL1Minutos.getText()),Double.parseDouble(txtL1Segundos.getText()));
          Lectura2 = Calculo.conversion(Double.parseDouble(txtL2Grados.getText()),Double.parseDouble(txtL2Minutos.getText()),Double.parseDouble(txtL2Segundos.getText()));
          Lectura3 = Calculo.conversion(Double.parseDouble(txtL3Grados.getText()),Double.parseDouble(txtL3Minutos.getText()),Double.parseDouble(txtL3Segundos.getText()));
          Lectura4 = Calculo.conversion(Double.parseDouble(txtL4Grados.getText()),Double.parseDouble(txtL4Minutos.getText()),Double.parseDouble(txtL4Segundos.getText()));
          
          Calculo.llenarMatris(Lectura1, Lectura2, Lectura3, Lectura4, numero );
          numero = numero +1;
          txtEstacion.setText(""+numero);
          
          txtL1Grados.setText("");
          txtL1Minutos.setText("");
          txtL1Segundos.setText("");
          
          txtL2Grados.setText("");
          txtL2Minutos.setText("");
          txtL2Segundos.setText("");
          
          txtL3Grados.setText("");
          txtL3Minutos.setText("");
          txtL3Segundos.setText("");
          
          txtL4Grados.setText("");
          txtL4Minutos.setText("");
          txtL4Segundos.setText("");
          
          txtDisXEst.setText("");
          
       }
       
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupodebtn;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTabbedPane tabbedp;
    private javax.swing.JTextField txtAIGrados;
    private javax.swing.JTextField txtAIMinutos;
    private javax.swing.JTextField txtAISegundos;
    private javax.swing.JTextField txtDeflexionG;
    private javax.swing.JTextField txtDeflexionM;
    private javax.swing.JTextField txtDeflexionS;
    private javax.swing.JTextField txtDisXEst;
    private javax.swing.JTextField txtDisXMoj;
    private javax.swing.JTextField txtEstacion;
    private javax.swing.JTextField txtL1Grados;
    private javax.swing.JTextField txtL1Minutos;
    private javax.swing.JTextField txtL1Segundos;
    private javax.swing.JTextField txtL2Grados;
    private javax.swing.JTextField txtL2Minutos;
    private javax.swing.JTextField txtL2Segundos;
    private javax.swing.JTextField txtL3Grados;
    private javax.swing.JTextField txtL3Minutos;
    private javax.swing.JTextField txtL3Segundos;
    private javax.swing.JTextField txtL4Grados;
    private javax.swing.JTextField txtL4Minutos;
    private javax.swing.JTextField txtL4Segundos;
    private javax.swing.JTextField txtLatitud;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextField txtNMojones;
    public static javax.swing.JTextField txtNVertices;
    private javax.swing.JTextField txtTAGrados;
    private javax.swing.JTextField txtTAMinutos;
    private javax.swing.JTextField txtTASegundos;
    private javax.swing.JRadioButton vistaaf;
    private javax.swing.JRadioButton vistaat;
    // End of variables declaration//GEN-END:variables
}
